version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - export BUILD_NAME=localimage
  build:
    commands:
      - mvn clean package
      - docker build -t $BUILD_NAME .
      - docker tag $BUILD_NAME:latest $IMAGE_URI
      - docker push $IMAGE_URI
      - echo "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URI\"}]" > imagedefinitions.json
artifacts:
  files:
    - 'imagedefinitions.json'