version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo $M2_HOME
      - sudo mvnw clean install
artifacts:
  files:
    - 'Dockerfile'
    - 'target/eb-demo-0.0.1-SNAPSHOT.jar'
